# Generated by Django 5.0.4 on 2024-04-25 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=15)),
                ('contrasena', models.CharField(max_length=15)),
            ],
        ),
    ]
