# Generated by Django 5.0.4 on 2024-04-26 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='correo',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
    ]
